apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: storage
type: Opaque
stringData:
  POSTGRES_USER: __POSTGRES_USER__
  POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
  POSTGRES_DB: __POSTGRES_DB__
  CHAINLINK_DB_USER: __CHAINLINK_USER__
  CHAINLINK_DB_PASSWORD: __CHAINLINK_PASSWORD_
  CHAINLINK_DB: __CHAINLINK_DB__